### ISSUE TITLE
...CurrentUser.LanguageOfUserInterface wirft eine Fehlermeldung

### ISSUE THREAD

**Issue by ralfthumel** [erminas/smartapi#2]
Hallo
..
Response.Write(sessionIntro.CurrentUser.LanguageOfUserInterface.Language);
...

Fehlermeldung
Serverfehler in der Anwendung /smartapi.
--------------------------------------------------------------------------------

Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt. 
Beschreibung: Unbehandelte Ausnahme beim Ausführen der aktuellen Webanforderung. Überprüfen Sie die Stapelüberwachung, um weitere Informationen über diesen Fehler anzuzeigen und festzustellen, wo der Fehler im Code verursacht wurde. 

Ausnahmedetails: System.ArgumentException: Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt.

Ursache: vermutlich ein Fehler im CMS LanguageIDs wurde mehrfach vergeben
Auszug aus dem RDCMS.log

    &lt;LIST id="PAN" country="Pakistan" language="Punjabi" standardlanguage="0" lcid="2118" rfclanguageid="pa-Arab-PK" /&gt;
    &lt;LIST id="PAN" country="India" language="Punjabi" standardlanguage="0" lcid="1094" rfclanguageid="pa-IN" /&gt;
    &lt;LIST id="TAM" country="India" language="Tamil" standardlanguage="0" lcid="1097" rfclanguageid="ta-IN" /&gt;
    &lt;LIST id="TAM" country="Sri Lanka" language="Tamil" standardlanguage="0" lcid="2121" rfclanguageid="ta-LK" /&gt;
    &lt;LIST id="TIR" country="Eritrea" language="Tigrinya" standardlanguage="0" lcid="2163" rfclanguageid="ti-ER" /&gt;
    &lt;LIST id="TIR" country="Ethiopia" language="Tigrinya" standardlanguage="0" lcid="1139" rfclanguageid="ti-ET" /&gt;
    &lt;LIST id="TSN" country="Botswana" language="Setswana" standardlanguage="0" lcid="2098" rfclanguageid="tn-BW" /&gt;
    &lt;LIST id="TSN" country="South Africa" language="Setswana" standardlanguage="0" lcid="1074" rfclanguageid="tn-ZA" /&gt;
    &lt;LIST id="TZM" country="Algeria" language="Central Atlas Tamazight (Latin)" standardlanguage="0" lcid="2143" rfclanguageid="tzm-Latn-DZ" /&gt;
    &lt;LIST id="TZM" country="Morocco" language="Central Atlas Tamazight (Tifinagh)" standardlanguage="0" lcid="4191" rfclanguageid="tzm-Tfng-MA" /&gt;
    &lt;LIST id="UZB" country="Uzbekistan" language="Uzbek (Cyrillic)" standardlanguage="0" lcid="2115" rfclanguageid="uz-Cyrl-UZ" /&gt;
    &lt;LIST id="UZB" country="Uzbekistan" language="Uzbek (Latin)" standardlanguage="0" lcid="1091" rfclanguageid="uz-Latn-UZ" /&gt;
	
Aufgefallen ist das in Version
Management Server 11.2 Build 11.2.2.1090 

Mit freundlichen Grüßen
Ralf Thumel

**Comment by jjacobi** [comment]
Auch wenn es etwas her ist.
Mit der aktuellen 11.2 Version kann ich das nicht reproduzieren (und es ist imho definitiv ein Fehler auf CMS Seite, denn alle Sprachreferenzen wuerden dadurch uneindeutig).

Falls das Problem weiterhin besteht, bitte nochmals oeffnen
